# Generated by Django 5.0.3 on 2024-03-31 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingArchive',
            fields=[
                ('hotel_id', models.IntegerField()),
                ('room_num', models.IntegerField()),
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('check_in_date', models.CharField(max_length=100)),
                ('check_out_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('identification_type', models.CharField(max_length=100)),
                ('identification_value', models.CharField(max_length=100)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelChain',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('office_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RentingArchive',
            fields=[
                ('hotel_id', models.IntegerField()),
                ('room_num', models.IntegerField()),
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('check_in_date', models.CharField(max_length=100)),
                ('check_out_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('ssn', models.IntegerField()),
                ('position', models.CharField(max_length=100)),
                ('works_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employing', to='hotel_system.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=100)),
                ('num_rooms', models.PositiveIntegerField()),
                ('star_rating', models.IntegerField()),
                ('email_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('managed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_system.employee')),
                ('hotel_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='hotel_system.hotelchain')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='works_at',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hotel_system.hotel'),
        ),
        migrations.CreateModel(
            name='ChainPhoneNumber',
            fields=[
                ('phone_number', models.IntegerField(primary_key=True, serialize=False)),
                ('hotel_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_system.hotelchain')),
            ],
        ),
        migrations.CreateModel(
            name='ChainEmailAddress',
            fields=[
                ('email_address', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('hotel_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_system.hotelchain')),
            ],
        ),
        migrations.CreateModel(
            name='HotelPhoneNumbers',
            fields=[
                ('phone_number', models.IntegerField(primary_key=True, serialize=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_system.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('capacity', models.IntegerField()),
                ('is_extendable', models.BooleanField()),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel_system.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_reported', models.CharField(max_length=100)),
                ('issue_type', models.CharField(max_length=100)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='hotel_system.room')),
            ],
        ),
        migrations.CreateModel(
            name='BookingOrder',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('check_in_date', models.DateTimeField()),
                ('check_out_date', models.DateTimeField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_system.customer')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='hotel_system.room')),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_type', models.CharField(max_length=100)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='hotel_system.room')),
            ],
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(check=models.Q(('ssn__gte', 100000000), ('ssn__lt', 999999999)), name='must enter valid ssn'),
        ),
        migrations.AddConstraint(
            model_name='hotel',
            constraint=models.CheckConstraint(check=models.Q(('star_rating__gte', 1), ('star_rating__lt', 5)), name='star rating must be between 1 and 5'),
        ),
        migrations.AddConstraint(
            model_name='chainphonenumber',
            constraint=models.CheckConstraint(check=models.Q(('phone_number__gte', 1000000000), ('phone_number__lt', 9999999999)), name='must enter valid phone number'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('hotel_id', 'room_num'), name='Room primary key'),
        ),
        migrations.AddConstraint(
            model_name='amenity',
            constraint=models.UniqueConstraint(fields=('room_id', 'amenity_type'), name='Amenity primary key'),
        ),
    ]
