# Generated by Django 5.0.3 on 2024-03-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hotel',
            name='star rating must be between 1 and 5',
        ),
        migrations.RenameField(
            model_name='amenity',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='amenity',
            old_name='amenity_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='bookingorder',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='bookingorder',
            old_name='booking_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='bookingorder',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='chainemailaddress',
            old_name='hotel_chain',
            new_name='chain',
        ),
        migrations.RenameField(
            model_name='chainphonenumber',
            old_name='hotel_chain',
            new_name='chain',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='city',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_chain',
            new_name='chain',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='issue_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='issue_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='hotel_id',
            new_name='hotel',
        ),
        migrations.AddConstraint(
            model_name='hotel',
            constraint=models.CheckConstraint(check=models.Q(('star_rating__gte', 1), ('star_rating__lte', 5)), name='star rating must be between 1 and 5'),
        ),
    ]
