# Generated by Django 5.0.3 on 2024-03-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_system', '0002_remove_hotel_star_rating_must_be_between_1_and_5_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='amenity',
            name='Amenity primary key',
        ),
        migrations.RemoveConstraint(
            model_name='room',
            name='Room primary key',
        ),
        migrations.AddConstraint(
            model_name='amenity',
            constraint=models.UniqueConstraint(fields=('room', 'type'), name='Amenity primary key'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('hotel', 'room_num'), name='Room primary key'),
        ),
    ]
